/**
 * Static model registry for all supported providers.
 * Ratings are 0–100 for: extraction, synthesis, reasoning, writing.
 * Pricing is per 1M tokens (USD). Context in tokens.
 */

export interface ModelSpec {
  id: string;
  provider: string;
  name: string;
  description: string;
  contextTokens: number;
  pricing: { input: number; output: number };
  ratings: { extraction: number; synthesis: number; reasoning: number; writing: number };
}

export const MODEL_REGISTRY: ModelSpec[] = [
  // ── OpenAI ──
  {
    id: 'gpt-4.1',
    provider: 'openai',
    name: 'GPT-4.1',
    description: 'Flagship model — excellent at complex reasoning and long-form generation',
    contextTokens: 1_048_576,
    pricing: { input: 2.0, output: 8.0 },
    ratings: { extraction: 92, synthesis: 94, reasoning: 95, writing: 93 },
  },
  {
    id: 'gpt-4.1-mini',
    provider: 'openai',
    name: 'GPT-4.1 Mini',
    description: 'Balanced cost-performance for everyday tasks',
    contextTokens: 1_048_576,
    pricing: { input: 0.4, output: 1.6 },
    ratings: { extraction: 85, synthesis: 86, reasoning: 84, writing: 85 },
  },
  {
    id: 'gpt-4.1-nano',
    provider: 'openai',
    name: 'GPT-4.1 Nano',
    description: 'Ultra-fast, lowest cost — ideal for simple extraction',
    contextTokens: 1_048_576,
    pricing: { input: 0.1, output: 0.4 },
    ratings: { extraction: 75, synthesis: 72, reasoning: 68, writing: 70 },
  },
  {
    id: 'o3',
    provider: 'openai',
    name: 'o3',
    description: 'Advanced reasoning model with extended thinking',
    contextTokens: 200_000,
    pricing: { input: 10.0, output: 40.0 },
    ratings: { extraction: 90, synthesis: 92, reasoning: 99, writing: 88 },
  },
  {
    id: 'o3-mini',
    provider: 'openai',
    name: 'o3-mini',
    description: 'Compact reasoning model — fast and efficient',
    contextTokens: 200_000,
    pricing: { input: 1.1, output: 4.4 },
    ratings: { extraction: 82, synthesis: 83, reasoning: 91, writing: 80 },
  },
  {
    id: 'o4-mini',
    provider: 'openai',
    name: 'o4-mini',
    description: 'Latest cost-effective reasoning model',
    contextTokens: 200_000,
    pricing: { input: 1.1, output: 4.4 },
    ratings: { extraction: 84, synthesis: 85, reasoning: 93, writing: 82 },
  },
  {
    id: 'o1',
    provider: 'openai',
    name: 'o1',
    description: 'First-gen reasoning model with chain-of-thought',
    contextTokens: 200_000,
    pricing: { input: 15.0, output: 60.0 },
    ratings: { extraction: 88, synthesis: 90, reasoning: 96, writing: 86 },
  },
  {
    id: 'o1-mini',
    provider: 'openai',
    name: 'o1-mini',
    description: 'Compact first-gen reasoning model',
    contextTokens: 128_000,
    pricing: { input: 3.0, output: 12.0 },
    ratings: { extraction: 80, synthesis: 81, reasoning: 89, writing: 78 },
  },
  {
    id: 'o1-preview',
    provider: 'openai',
    name: 'o1-preview',
    description: 'Preview of o1 reasoning capabilities',
    contextTokens: 128_000,
    pricing: { input: 15.0, output: 60.0 },
    ratings: { extraction: 87, synthesis: 89, reasoning: 95, writing: 85 },
  },
  {
    id: 'gpt-4o',
    provider: 'openai',
    name: 'GPT-4o',
    description: 'Multimodal flagship with vision and audio',
    contextTokens: 128_000,
    pricing: { input: 2.5, output: 10.0 },
    ratings: { extraction: 90, synthesis: 91, reasoning: 92, writing: 91 },
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    name: 'GPT-4o Mini',
    description: 'Compact multimodal model',
    contextTokens: 128_000,
    pricing: { input: 0.15, output: 0.6 },
    ratings: { extraction: 80, synthesis: 80, reasoning: 78, writing: 79 },
  },
  {
    id: 'gpt-4-turbo',
    provider: 'openai',
    name: 'GPT-4 Turbo',
    description: 'Previous generation flagship with vision',
    contextTokens: 128_000,
    pricing: { input: 10.0, output: 30.0 },
    ratings: { extraction: 88, synthesis: 89, reasoning: 90, writing: 90 },
  },
  {
    id: 'gpt-4',
    provider: 'openai',
    name: 'GPT-4',
    description: 'Original GPT-4 — reliable reasoning',
    contextTokens: 8_192,
    pricing: { input: 30.0, output: 60.0 },
    ratings: { extraction: 86, synthesis: 87, reasoning: 88, writing: 88 },
  },
  {
    id: 'gpt-3.5-turbo',
    provider: 'openai',
    name: 'GPT-3.5 Turbo',
    description: 'Legacy fast model — lowest cost for simple tasks',
    contextTokens: 16_385,
    pricing: { input: 0.5, output: 1.5 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 65, writing: 72 },
  },
  {
    id: 'gpt-4o-realtime-preview',
    provider: 'openai',
    name: 'GPT-4o Realtime Preview',
    description: 'Real-time audio/video processing model',
    contextTokens: 128_000,
    pricing: { input: 5.0, output: 20.0 },
    ratings: { extraction: 88, synthesis: 89, reasoning: 90, writing: 89 },
  },
  {
    id: 'gpt-4o-audio-preview',
    provider: 'openai',
    name: 'GPT-4o Audio Preview',
    description: 'Audio-capable multimodal model',
    contextTokens: 128_000,
    pricing: { input: 2.5, output: 10.0 },
    ratings: { extraction: 88, synthesis: 89, reasoning: 90, writing: 89 },
  },
  {
    id: 'chatgpt-4o-latest',
    provider: 'openai',
    name: 'ChatGPT-4o Latest',
    description: 'Latest ChatGPT-optimized variant of GPT-4o',
    contextTokens: 128_000,
    pricing: { input: 5.0, output: 15.0 },
    ratings: { extraction: 90, synthesis: 91, reasoning: 92, writing: 91 },
  },
  {
    id: 'text-embedding-3-small',
    provider: 'openai',
    name: 'Text Embedding 3 Small',
    description: 'Compact embedding model for vector search',
    contextTokens: 8_191,
    pricing: { input: 0.02, output: 0 },
    ratings: { extraction: 60, synthesis: 40, reasoning: 30, writing: 30 },
  },
  {
    id: 'text-embedding-3-large',
    provider: 'openai',
    name: 'Text Embedding 3 Large',
    description: 'High-quality embedding model for semantic search',
    contextTokens: 8_191,
    pricing: { input: 0.13, output: 0 },
    ratings: { extraction: 65, synthesis: 45, reasoning: 35, writing: 35 },
  },
  {
    id: 'text-embedding-ada-002',
    provider: 'openai',
    name: 'Text Embedding Ada 002',
    description: 'Legacy embedding model',
    contextTokens: 8_191,
    pricing: { input: 0.1, output: 0 },
    ratings: { extraction: 58, synthesis: 38, reasoning: 28, writing: 28 },
  },
  {
    id: 'whisper-1',
    provider: 'openai',
    name: 'Whisper-1',
    description: 'Speech-to-text transcription model',
    contextTokens: 0,
    pricing: { input: 0.36, output: 0 },
    ratings: { extraction: 85, synthesis: 30, reasoning: 20, writing: 30 },
  },
  {
    id: 'tts-1',
    provider: 'openai',
    name: 'TTS-1',
    description: 'Text-to-speech standard quality',
    contextTokens: 4_096,
    pricing: { input: 15.0, output: 0 },
    ratings: { extraction: 30, synthesis: 30, reasoning: 20, writing: 70 },
  },
  {
    id: 'tts-1-hd',
    provider: 'openai',
    name: 'TTS-1 HD',
    description: 'Text-to-speech high-definition quality',
    contextTokens: 4_096,
    pricing: { input: 30.0, output: 0 },
    ratings: { extraction: 30, synthesis: 30, reasoning: 20, writing: 75 },
  },
  {
    id: 'dall-e-3',
    provider: 'openai',
    name: 'DALL·E 3',
    description: 'Image generation from text prompts',
    contextTokens: 4_096,
    pricing: { input: 40.0, output: 0 },
    ratings: { extraction: 30, synthesis: 80, reasoning: 30, writing: 30 },
  },
  {
    id: 'dall-e-2',
    provider: 'openai',
    name: 'DALL·E 2',
    description: 'Previous generation image model',
    contextTokens: 1_024,
    pricing: { input: 20.0, output: 0 },
    ratings: { extraction: 25, synthesis: 70, reasoning: 25, writing: 25 },
  },

  // ── Anthropic ──
  {
    id: 'claude-opus-4',
    provider: 'anthropic',
    name: 'Claude Opus 4',
    description: 'Most capable Anthropic model — superior reasoning and analysis',
    contextTokens: 200_000,
    pricing: { input: 15.0, output: 75.0 },
    ratings: { extraction: 96, synthesis: 97, reasoning: 98, writing: 97 },
  },
  {
    id: 'claude-sonnet-4-6',
    provider: 'anthropic',
    name: 'Claude Sonnet 4.6',
    description: 'Best balance of quality & speed — excellent for structured extraction',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 95, synthesis: 94, reasoning: 94, writing: 96 },
  },
  {
    id: 'claude-sonnet-4',
    provider: 'anthropic',
    name: 'Claude Sonnet 4',
    description: 'High-quality Sonnet model — great all-around',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 93, synthesis: 93, reasoning: 93, writing: 95 },
  },
  {
    id: 'claude-3.5-sonnet-20241022',
    provider: 'anthropic',
    name: 'Claude 3.5 Sonnet (Oct 2024)',
    description: 'Updated Sonnet — excellent coding and analysis',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 92, synthesis: 91, reasoning: 91, writing: 94 },
  },
  {
    id: 'claude-3.5-sonnet-20240620',
    provider: 'anthropic',
    name: 'Claude 3.5 Sonnet (Jun 2024)',
    description: 'Original 3.5 Sonnet release',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 91, synthesis: 90, reasoning: 90, writing: 93 },
  },
  {
    id: 'claude-haiku-3.5',
    provider: 'anthropic',
    name: 'Claude Haiku 3.5',
    description: 'Ultra-fast and affordable — great for high-volume tasks',
    contextTokens: 200_000,
    pricing: { input: 0.8, output: 4.0 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 78, writing: 80 },
  },
  {
    id: 'claude-3-opus-20240229',
    provider: 'anthropic',
    name: 'Claude 3 Opus',
    description: 'Previous gen most powerful model',
    contextTokens: 200_000,
    pricing: { input: 15.0, output: 75.0 },
    ratings: { extraction: 94, synthesis: 95, reasoning: 96, writing: 95 },
  },
  {
    id: 'claude-3-sonnet-20240229',
    provider: 'anthropic',
    name: 'Claude 3 Sonnet',
    description: 'Previous gen balanced model',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 85, synthesis: 84, reasoning: 84, writing: 86 },
  },
  {
    id: 'claude-3-haiku',
    provider: 'anthropic',
    name: 'Claude 3 Haiku',
    description: 'Legacy compact model — near-instant responses',
    contextTokens: 200_000,
    pricing: { input: 0.25, output: 1.25 },
    ratings: { extraction: 75, synthesis: 73, reasoning: 70, writing: 74 },
  },
  {
    id: 'claude-2.1',
    provider: 'anthropic',
    name: 'Claude 2.1',
    description: 'Legacy model with 200K context',
    contextTokens: 200_000,
    pricing: { input: 8.0, output: 24.0 },
    ratings: { extraction: 78, synthesis: 77, reasoning: 76, writing: 80 },
  },
  {
    id: 'claude-2.0',
    provider: 'anthropic',
    name: 'Claude 2.0',
    description: 'Legacy general-purpose model',
    contextTokens: 100_000,
    pricing: { input: 8.0, output: 24.0 },
    ratings: { extraction: 76, synthesis: 75, reasoning: 74, writing: 78 },
  },
  {
    id: 'claude-instant-1.2',
    provider: 'anthropic',
    name: 'Claude Instant 1.2',
    description: 'Legacy fast and affordable model',
    contextTokens: 100_000,
    pricing: { input: 0.8, output: 2.4 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 65, writing: 72 },
  },

  // ── Google ──
  {
    id: 'gemini-2.5-pro',
    provider: 'google',
    name: 'Gemini 2.5 Pro',
    description: 'Thinking model — advanced reasoning with long context',
    contextTokens: 1_048_576,
    pricing: { input: 1.25, output: 10.0 },
    ratings: { extraction: 93, synthesis: 93, reasoning: 96, writing: 92 },
  },
  {
    id: 'gemini-2.5-flash',
    provider: 'google',
    name: 'Gemini 2.5 Flash',
    description: 'Fast thinking model — good for everyday workloads',
    contextTokens: 1_048_576,
    pricing: { input: 0.15, output: 0.6 },
    ratings: { extraction: 86, synthesis: 85, reasoning: 87, writing: 84 },
  },
  {
    id: 'gemini-2.5-flash-lite',
    provider: 'google',
    name: 'Gemini 2.5 Flash Lite',
    description: 'Ultra-lightweight flash variant',
    contextTokens: 1_048_576,
    pricing: { input: 0.04, output: 0.15 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 72, writing: 70 },
  },
  {
    id: 'gemini-2.0-flash',
    provider: 'google',
    name: 'Gemini 2.0 Flash',
    description: 'Balanced speed and quality with multimodal support',
    contextTokens: 1_048_576,
    pricing: { input: 0.1, output: 0.4 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 80, writing: 78 },
  },
  {
    id: 'gemini-2.0-flash-lite',
    provider: 'google',
    name: 'Gemini 2.0 Flash-Lite',
    description: 'Lightweight and cost-efficient for simple tasks',
    contextTokens: 1_048_576,
    pricing: { input: 0.04, output: 0.15 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 68, writing: 68 },
  },
  {
    id: 'gemini-2.0-flash-thinking-exp',
    provider: 'google',
    name: 'Gemini 2.0 Flash Thinking',
    description: 'Experimental thinking-enabled flash model',
    contextTokens: 1_048_576,
    pricing: { input: 0.1, output: 0.4 },
    ratings: { extraction: 84, synthesis: 82, reasoning: 85, writing: 80 },
  },
  {
    id: 'gemini-1.5-pro',
    provider: 'google',
    name: 'Gemini 1.5 Pro',
    description: 'Previous gen with 2M context for very long documents',
    contextTokens: 2_097_152,
    pricing: { input: 1.25, output: 5.0 },
    ratings: { extraction: 88, synthesis: 87, reasoning: 88, writing: 86 },
  },
  {
    id: 'gemini-1.5-flash',
    provider: 'google',
    name: 'Gemini 1.5 Flash',
    description: 'Previous gen fast model with long context',
    contextTokens: 1_048_576,
    pricing: { input: 0.075, output: 0.3 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 75, writing: 74 },
  },
  {
    id: 'gemini-1.5-flash-8b',
    provider: 'google',
    name: 'Gemini 1.5 Flash 8B',
    description: 'Compact 8B flash model — fastest Google option',
    contextTokens: 1_048_576,
    pricing: { input: 0.0375, output: 0.15 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 66, writing: 66 },
  },
  {
    id: 'gemini-1.0-pro',
    provider: 'google',
    name: 'Gemini 1.0 Pro',
    description: 'Legacy Gemini model',
    contextTokens: 32_760,
    pricing: { input: 0.5, output: 1.5 },
    ratings: { extraction: 75, synthesis: 73, reasoning: 72, writing: 72 },
  },
  {
    id: 'gemini-pro-vision',
    provider: 'google',
    name: 'Gemini Pro Vision',
    description: 'Legacy vision-capable Gemini',
    contextTokens: 16_384,
    pricing: { input: 0.5, output: 1.5 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 71, writing: 70 },
  },
  {
    id: 'text-embedding-004',
    provider: 'google',
    name: 'Text Embedding 004',
    description: 'Google text embedding model',
    contextTokens: 2_048,
    pricing: { input: 0.025, output: 0 },
    ratings: { extraction: 62, synthesis: 42, reasoning: 32, writing: 32 },
  },
  {
    id: 'embedding-001',
    provider: 'google',
    name: 'Embedding 001',
    description: 'Legacy Google embedding',
    contextTokens: 2_048,
    pricing: { input: 0.025, output: 0 },
    ratings: { extraction: 58, synthesis: 38, reasoning: 28, writing: 28 },
  },
  {
    id: 'imagen-3.0-generate-002',
    provider: 'google',
    name: 'Imagen 3.0',
    description: 'Image generation model',
    contextTokens: 4_096,
    pricing: { input: 40.0, output: 0 },
    ratings: { extraction: 25, synthesis: 78, reasoning: 25, writing: 25 },
  },

  // ── Groq ──
  {
    id: 'llama-3.3-70b-versatile',
    provider: 'groq',
    name: 'Llama 3.3 70B',
    description: 'High-quality open model with blazing-fast inference',
    contextTokens: 128_000,
    pricing: { input: 0.59, output: 0.79 },
    ratings: { extraction: 83, synthesis: 82, reasoning: 82, writing: 81 },
  },
  {
    id: 'llama-3.1-70b-versatile',
    provider: 'groq',
    name: 'Llama 3.1 70B',
    description: 'Previous gen 70B — strong general performance',
    contextTokens: 128_000,
    pricing: { input: 0.59, output: 0.79 },
    ratings: { extraction: 80, synthesis: 79, reasoning: 80, writing: 78 },
  },
  {
    id: 'llama-3.1-8b-instant',
    provider: 'groq',
    name: 'Llama 3.1 8B',
    description: 'Ultra-fast small model — best for low-latency tasks',
    contextTokens: 128_000,
    pricing: { input: 0.05, output: 0.08 },
    ratings: { extraction: 68, synthesis: 65, reasoning: 62, writing: 64 },
  },
  {
    id: 'llama-3.2-90b-vision-preview',
    provider: 'groq',
    name: 'Llama 3.2 90B Vision',
    description: 'Large vision model — multimodal with image input',
    contextTokens: 128_000,
    pricing: { input: 0.9, output: 0.9 },
    ratings: { extraction: 85, synthesis: 83, reasoning: 84, writing: 82 },
  },
  {
    id: 'llama-3.2-11b-vision-preview',
    provider: 'groq',
    name: 'Llama 3.2 11B Vision',
    description: 'Compact vision model with image understanding',
    contextTokens: 128_000,
    pricing: { input: 0.18, output: 0.18 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 68, writing: 68 },
  },
  {
    id: 'llama-3.2-3b-preview',
    provider: 'groq',
    name: 'Llama 3.2 3B',
    description: 'Compact model — fastest latency for basic tasks',
    contextTokens: 128_000,
    pricing: { input: 0.06, output: 0.06 },
    ratings: { extraction: 62, synthesis: 58, reasoning: 55, writing: 58 },
  },
  {
    id: 'llama-3.2-1b-preview',
    provider: 'groq',
    name: 'Llama 3.2 1B',
    description: 'Smallest Llama — edge-level inference',
    contextTokens: 128_000,
    pricing: { input: 0.04, output: 0.04 },
    ratings: { extraction: 55, synthesis: 50, reasoning: 45, writing: 50 },
  },
  {
    id: 'llama3-groq-70b-tool-use',
    provider: 'groq',
    name: 'Llama 3 70B Tool Use',
    description: 'Optimized for function calling / tool use',
    contextTokens: 8_192,
    pricing: { input: 0.89, output: 0.89 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 82, writing: 78 },
  },
  {
    id: 'llama3-groq-8b-tool-use',
    provider: 'groq',
    name: 'Llama 3 8B Tool Use',
    description: 'Compact model optimized for function calling',
    contextTokens: 8_192,
    pricing: { input: 0.19, output: 0.19 },
    ratings: { extraction: 68, synthesis: 64, reasoning: 66, writing: 62 },
  },
  {
    id: 'llama3-70b-8192',
    provider: 'groq',
    name: 'Llama 3 70B',
    description: 'Meta Llama 3 70B — strong open-source model',
    contextTokens: 8_192,
    pricing: { input: 0.59, output: 0.79 },
    ratings: { extraction: 80, synthesis: 78, reasoning: 79, writing: 77 },
  },
  {
    id: 'llama3-8b-8192',
    provider: 'groq',
    name: 'Llama 3 8B',
    description: 'Compact Llama 3 — fast inference',
    contextTokens: 8_192,
    pricing: { input: 0.05, output: 0.08 },
    ratings: { extraction: 66, synthesis: 63, reasoning: 60, writing: 62 },
  },
  {
    id: 'mixtral-8x7b-32768',
    provider: 'groq',
    name: 'Mixtral 8x7B',
    description: 'Sparse MoE model with strong multilingual performance',
    contextTokens: 32_768,
    pricing: { input: 0.24, output: 0.24 },
    ratings: { extraction: 75, synthesis: 74, reasoning: 73, writing: 74 },
  },
  {
    id: 'gemma2-9b-it',
    provider: 'groq',
    name: 'Gemma 2 9B',
    description: 'Google Gemma — compact and efficient',
    contextTokens: 8_192,
    pricing: { input: 0.2, output: 0.2 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 66, writing: 68 },
  },
  {
    id: 'gemma-7b-it',
    provider: 'groq',
    name: 'Gemma 7B',
    description: 'First-gen Google Gemma model',
    contextTokens: 8_192,
    pricing: { input: 0.07, output: 0.07 },
    ratings: { extraction: 64, synthesis: 62, reasoning: 60, writing: 62 },
  },
  {
    id: 'whisper-large-v3',
    provider: 'groq',
    name: 'Whisper Large v3',
    description: 'Speech-to-text via Groq — extremely fast transcription',
    contextTokens: 0,
    pricing: { input: 0.111, output: 0 },
    ratings: { extraction: 88, synthesis: 30, reasoning: 20, writing: 30 },
  },
  {
    id: 'whisper-large-v3-turbo',
    provider: 'groq',
    name: 'Whisper Large v3 Turbo',
    description: 'Fastest Whisper variant on Groq',
    contextTokens: 0,
    pricing: { input: 0.04, output: 0 },
    ratings: { extraction: 85, synthesis: 30, reasoning: 20, writing: 30 },
  },
  {
    id: 'distil-whisper-large-v3-en',
    provider: 'groq',
    name: 'Distil Whisper v3 EN',
    description: 'Distilled English-only Whisper — ultra-fast',
    contextTokens: 0,
    pricing: { input: 0.02, output: 0 },
    ratings: { extraction: 82, synthesis: 30, reasoning: 20, writing: 30 },
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    provider: 'groq',
    name: 'DeepSeek R1 70B',
    description: 'Reasoning-focused distilled model',
    contextTokens: 128_000,
    pricing: { input: 0.75, output: 0.99 },
    ratings: { extraction: 80, synthesis: 80, reasoning: 88, writing: 78 },
  },
  {
    id: 'qwen-qwq-32b',
    provider: 'groq',
    name: 'Qwen QwQ 32B',
    description: 'Alibaba reasoning model with strong multilingual',
    contextTokens: 128_000,
    pricing: { input: 0.29, output: 0.39 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 85, writing: 75 },
  },
  {
    id: 'qwen-2.5-coder-32b',
    provider: 'groq',
    name: 'Qwen 2.5 Coder 32B',
    description: 'Code-specialized Qwen model',
    contextTokens: 128_000,
    pricing: { input: 0.29, output: 0.39 },
    ratings: { extraction: 75, synthesis: 73, reasoning: 82, writing: 72 },
  },
  {
    id: 'qwen-2.5-32b',
    provider: 'groq',
    name: 'Qwen 2.5 32B',
    description: 'General-purpose Qwen 2.5 model',
    contextTokens: 128_000,
    pricing: { input: 0.29, output: 0.39 },
    ratings: { extraction: 76, synthesis: 75, reasoning: 78, writing: 74 },
  },
  {
    id: 'llama-guard-3-8b',
    provider: 'groq',
    name: 'Llama Guard 3 8B',
    description: 'Content safety classifier model',
    contextTokens: 8_192,
    pricing: { input: 0.2, output: 0.2 },
    ratings: { extraction: 65, synthesis: 40, reasoning: 55, writing: 40 },
  },

  // ── Ollama (local, free) ──
  {
    id: 'llama3.3:70b',
    provider: 'ollama',
    name: 'Llama 3.3 70B (local)',
    description: 'Latest 70B Llama — needs 40GB+ VRAM',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 83, synthesis: 82, reasoning: 82, writing: 81 },
  },
  {
    id: 'llama3.2:latest',
    provider: 'ollama',
    name: 'Llama 3.2 (local)',
    description: 'Run Llama 3.2 locally — no API costs',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 68, writing: 70 },
  },
  {
    id: 'llama3.2:3b',
    provider: 'ollama',
    name: 'Llama 3.2 3B (local)',
    description: 'Compact Llama for fast inference',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 62, synthesis: 58, reasoning: 55, writing: 58 },
  },
  {
    id: 'llama3.2:1b',
    provider: 'ollama',
    name: 'Llama 3.2 1B (local)',
    description: 'Smallest Llama — edge-level',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 55, synthesis: 50, reasoning: 45, writing: 50 },
  },
  {
    id: 'llama3.2-vision:11b',
    provider: 'ollama',
    name: 'Llama 3.2 Vision 11B (local)',
    description: 'Vision-capable Llama model',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 68, writing: 68 },
  },
  {
    id: 'llama3.2-vision:90b',
    provider: 'ollama',
    name: 'Llama 3.2 Vision 90B (local)',
    description: 'Large vision Llama — needs 48GB+ VRAM',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 85, synthesis: 83, reasoning: 84, writing: 82 },
  },
  {
    id: 'llama3.1:latest',
    provider: 'ollama',
    name: 'Llama 3.1 8B (local)',
    description: 'Run Llama 3.1 8B locally — solid general performance',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 68, synthesis: 65, reasoning: 62, writing: 64 },
  },
  {
    id: 'llama3.1:70b',
    provider: 'ollama',
    name: 'Llama 3.1 70B (local)',
    description: 'Large local model — needs 40GB+ VRAM',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 80, synthesis: 79, reasoning: 80, writing: 78 },
  },
  {
    id: 'llama3.1:405b',
    provider: 'ollama',
    name: 'Llama 3.1 405B (local)',
    description: 'Largest open model — needs multi-GPU setup',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 90, synthesis: 89, reasoning: 90, writing: 88 },
  },
  {
    id: 'gemma3:27b',
    provider: 'ollama',
    name: 'Gemma 3 27B (local)',
    description: 'Google Gemma 3 — strong multilingual',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 75, writing: 75 },
  },
  {
    id: 'gemma3:12b',
    provider: 'ollama',
    name: 'Gemma 3 12B (local)',
    description: 'Mid-size Gemma 3 model',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 69, writing: 69 },
  },
  {
    id: 'gemma3:4b',
    provider: 'ollama',
    name: 'Gemma 3 4B (local)',
    description: 'Compact Gemma 3 — fast on CPU',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 65, synthesis: 63, reasoning: 62, writing: 62 },
  },
  {
    id: 'gemma2:latest',
    provider: 'ollama',
    name: 'Gemma 2 9B (local)',
    description: 'Google Gemma 2 — efficient and accurate',
    contextTokens: 8_192,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 66, writing: 68 },
  },
  {
    id: 'gemma2:27b',
    provider: 'ollama',
    name: 'Gemma 2 27B (local)',
    description: 'Large Gemma 2 — good quality',
    contextTokens: 8_192,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 76, synthesis: 74, reasoning: 73, writing: 73 },
  },
  {
    id: 'qwen2.5:72b',
    provider: 'ollama',
    name: 'Qwen 2.5 72B (local)',
    description: 'Large Qwen — excellent multilingual',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 83, writing: 80 },
  },
  {
    id: 'qwen2.5:32b',
    provider: 'ollama',
    name: 'Qwen 2.5 32B (local)',
    description: 'Mid-size Qwen with strong reasoning',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 76, synthesis: 75, reasoning: 78, writing: 74 },
  },
  {
    id: 'qwen2.5:latest',
    provider: 'ollama',
    name: 'Qwen 2.5 (local)',
    description: 'Alibaba Qwen — strong multilingual support',
    contextTokens: 32_768,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 71, synthesis: 69, reasoning: 70, writing: 69 },
  },
  {
    id: 'qwen2.5-coder:32b',
    provider: 'ollama',
    name: 'Qwen 2.5 Coder 32B (local)',
    description: 'Code-specialized model',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 80, writing: 70 },
  },
  {
    id: 'qwen3:32b',
    provider: 'ollama',
    name: 'Qwen 3 32B (local)',
    description: 'Latest Qwen generation — strong all-around',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 80, synthesis: 78, reasoning: 82, writing: 78 },
  },
  {
    id: 'qwen3:8b',
    provider: 'ollama',
    name: 'Qwen 3 8B (local)',
    description: 'Compact Qwen 3 — fast inference',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 72, writing: 68 },
  },
  {
    id: 'mistral:latest',
    provider: 'ollama',
    name: 'Mistral 7B (local)',
    description: 'Run Mistral locally — fast inference on CPU',
    contextTokens: 32_768,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 68, synthesis: 66, reasoning: 64, writing: 66 },
  },
  {
    id: 'mistral-nemo:12b',
    provider: 'ollama',
    name: 'Mistral Nemo 12B (local)',
    description: 'Mistral Nemo — balanced quality',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 70, writing: 70 },
  },
  {
    id: 'mistral-small:24b',
    provider: 'ollama',
    name: 'Mistral Small 24B (local)',
    description: 'Mid-size Mistral — good for general tasks',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 76, synthesis: 74, reasoning: 74, writing: 74 },
  },
  {
    id: 'mistral-large:123b',
    provider: 'ollama',
    name: 'Mistral Large 123B (local)',
    description: 'Largest Mistral — needs 64GB+ VRAM',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 84, synthesis: 83, reasoning: 84, writing: 83 },
  },
  {
    id: 'mixtral:latest',
    provider: 'ollama',
    name: 'Mixtral 8x7B (local)',
    description: 'MoE model — strong multilingual, needs 26GB+',
    contextTokens: 32_768,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 75, synthesis: 74, reasoning: 73, writing: 74 },
  },
  {
    id: 'phi4:14b',
    provider: 'ollama',
    name: 'Phi 4 14B (local)',
    description: 'Microsoft Phi 4 — strong reasoning',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 78, writing: 71 },
  },
  {
    id: 'phi3:latest',
    provider: 'ollama',
    name: 'Phi-3 (local)',
    description: 'Microsoft Phi-3 — small but capable',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 72, writing: 67 },
  },
  {
    id: 'deepseek-r1:latest',
    provider: 'ollama',
    name: 'DeepSeek R1 (local)',
    description: 'Reasoning-focused model — strong at analysis',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 78, synthesis: 77, reasoning: 86, writing: 75 },
  },
  {
    id: 'deepseek-r1:70b',
    provider: 'ollama',
    name: 'DeepSeek R1 70B (local)',
    description: 'Large reasoning model — needs 40GB+ VRAM',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 84, synthesis: 83, reasoning: 92, writing: 81 },
  },
  {
    id: 'deepseek-v3:671b',
    provider: 'ollama',
    name: 'DeepSeek V3 671B (local)',
    description: 'Largest DeepSeek — multi-GPU required',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 88, synthesis: 87, reasoning: 90, writing: 86 },
  },
  {
    id: 'codellama:70b',
    provider: 'ollama',
    name: 'Code Llama 70B (local)',
    description: 'Code generation — large model',
    contextTokens: 16_384,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 75, writing: 65 },
  },
  {
    id: 'codellama:34b',
    provider: 'ollama',
    name: 'Code Llama 34B (local)',
    description: 'Code generation — mid-size model',
    contextTokens: 16_384,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 66, synthesis: 64, reasoning: 72, writing: 62 },
  },
  {
    id: 'codellama:7b',
    provider: 'ollama',
    name: 'Code Llama 7B (local)',
    description: 'Compact code model',
    contextTokens: 16_384,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 58, synthesis: 56, reasoning: 64, writing: 54 },
  },
  {
    id: 'command-r-plus:104b',
    provider: 'ollama',
    name: 'Command R+ 104B (local)',
    description: 'Cohere Command R+ — RAG-optimized',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 86, synthesis: 84, reasoning: 82, writing: 83 },
  },
  {
    id: 'command-r:35b',
    provider: 'ollama',
    name: 'Command R 35B (local)',
    description: 'Cohere Command R — good for retrieval',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 74, writing: 75 },
  },
  {
    id: 'nomic-embed-text:latest',
    provider: 'ollama',
    name: 'Nomic Embed (local)',
    description: 'Text embedding model for vector search',
    contextTokens: 8_192,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 60, synthesis: 40, reasoning: 30, writing: 30 },
  },
  {
    id: 'mxbai-embed-large:latest',
    provider: 'ollama',
    name: 'MxBai Embed Large (local)',
    description: 'High-quality embedding model',
    contextTokens: 8_192,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 62, synthesis: 42, reasoning: 32, writing: 32 },
  },
  {
    id: 'all-minilm:latest',
    provider: 'ollama',
    name: 'All-MiniLM (local)',
    description: 'Lightweight sentence embedding',
    contextTokens: 512,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 55, synthesis: 35, reasoning: 25, writing: 25 },
  },
  {
    id: 'llava:34b',
    provider: 'ollama',
    name: 'LLaVA 34B (local)',
    description: 'Large vision-language model',
    contextTokens: 4_096,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 68, writing: 68 },
  },
  {
    id: 'llava:7b',
    provider: 'ollama',
    name: 'LLaVA 7B (local)',
    description: 'Compact vision-language model',
    contextTokens: 4_096,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 62, synthesis: 60, reasoning: 58, writing: 58 },
  },

  // ── OpenRouter (popular models as offline fallback) ──
  {
    id: 'anthropic/claude-sonnet-4-6',
    provider: 'openrouter',
    name: 'Claude Sonnet 4.6 (OR)',
    description: 'Claude Sonnet 4.6 via OpenRouter gateway',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 95, synthesis: 94, reasoning: 94, writing: 96 },
  },
  {
    id: 'anthropic/claude-opus-4',
    provider: 'openrouter',
    name: 'Claude Opus 4 (OR)',
    description: 'Claude Opus 4 via OpenRouter — most powerful',
    contextTokens: 200_000,
    pricing: { input: 15.0, output: 75.0 },
    ratings: { extraction: 96, synthesis: 97, reasoning: 98, writing: 97 },
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    provider: 'openrouter',
    name: 'Claude 3.5 Sonnet (OR)',
    description: 'Claude 3.5 Sonnet via OpenRouter',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 92, synthesis: 91, reasoning: 91, writing: 94 },
  },
  {
    id: 'anthropic/claude-3.5-haiku',
    provider: 'openrouter',
    name: 'Claude 3.5 Haiku (OR)',
    description: 'Claude Haiku via OpenRouter — fast & cheap',
    contextTokens: 200_000,
    pricing: { input: 0.8, output: 4.0 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 78, writing: 80 },
  },
  {
    id: 'anthropic/claude-3-opus',
    provider: 'openrouter',
    name: 'Claude 3 Opus (OR)',
    description: 'Claude 3 Opus via OpenRouter',
    contextTokens: 200_000,
    pricing: { input: 15.0, output: 75.0 },
    ratings: { extraction: 94, synthesis: 95, reasoning: 96, writing: 95 },
  },
  {
    id: 'openai/gpt-4.1',
    provider: 'openrouter',
    name: 'GPT-4.1 (OR)',
    description: 'GPT-4.1 via OpenRouter gateway',
    contextTokens: 1_048_576,
    pricing: { input: 2.0, output: 8.0 },
    ratings: { extraction: 92, synthesis: 94, reasoning: 95, writing: 93 },
  },
  {
    id: 'openai/gpt-4.1-mini',
    provider: 'openrouter',
    name: 'GPT-4.1 Mini (OR)',
    description: 'GPT-4.1 Mini via OpenRouter gateway',
    contextTokens: 1_048_576,
    pricing: { input: 0.4, output: 1.6 },
    ratings: { extraction: 85, synthesis: 86, reasoning: 84, writing: 85 },
  },
  {
    id: 'openai/gpt-4.1-nano',
    provider: 'openrouter',
    name: 'GPT-4.1 Nano (OR)',
    description: 'GPT-4.1 Nano via OpenRouter — cheapest',
    contextTokens: 1_048_576,
    pricing: { input: 0.1, output: 0.4 },
    ratings: { extraction: 75, synthesis: 72, reasoning: 68, writing: 70 },
  },
  {
    id: 'openai/gpt-4o',
    provider: 'openrouter',
    name: 'GPT-4o (OR)',
    description: 'GPT-4o via OpenRouter gateway',
    contextTokens: 128_000,
    pricing: { input: 2.5, output: 10.0 },
    ratings: { extraction: 90, synthesis: 91, reasoning: 92, writing: 91 },
  },
  {
    id: 'openai/gpt-4o-mini',
    provider: 'openrouter',
    name: 'GPT-4o Mini (OR)',
    description: 'GPT-4o Mini via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.15, output: 0.6 },
    ratings: { extraction: 80, synthesis: 80, reasoning: 78, writing: 79 },
  },
  {
    id: 'openai/o3',
    provider: 'openrouter',
    name: 'o3 (OR)',
    description: 'OpenAI o3 reasoning model via OpenRouter',
    contextTokens: 200_000,
    pricing: { input: 10.0, output: 40.0 },
    ratings: { extraction: 90, synthesis: 92, reasoning: 99, writing: 88 },
  },
  {
    id: 'openai/o3-mini',
    provider: 'openrouter',
    name: 'o3-mini (OR)',
    description: 'OpenAI o3-mini via OpenRouter',
    contextTokens: 200_000,
    pricing: { input: 1.1, output: 4.4 },
    ratings: { extraction: 82, synthesis: 83, reasoning: 91, writing: 80 },
  },
  {
    id: 'openai/o4-mini',
    provider: 'openrouter',
    name: 'o4-mini (OR)',
    description: 'OpenAI o4-mini via OpenRouter',
    contextTokens: 200_000,
    pricing: { input: 1.1, output: 4.4 },
    ratings: { extraction: 84, synthesis: 85, reasoning: 93, writing: 82 },
  },
  {
    id: 'google/gemini-2.5-pro-preview',
    provider: 'openrouter',
    name: 'Gemini 2.5 Pro (OR)',
    description: 'Gemini 2.5 Pro via OpenRouter gateway',
    contextTokens: 1_048_576,
    pricing: { input: 1.25, output: 10.0 },
    ratings: { extraction: 93, synthesis: 93, reasoning: 96, writing: 92 },
  },
  {
    id: 'google/gemini-2.5-flash-preview',
    provider: 'openrouter',
    name: 'Gemini 2.5 Flash (OR)',
    description: 'Gemini 2.5 Flash via OpenRouter',
    contextTokens: 1_048_576,
    pricing: { input: 0.15, output: 0.6 },
    ratings: { extraction: 86, synthesis: 85, reasoning: 87, writing: 84 },
  },
  {
    id: 'google/gemini-2.0-flash-001',
    provider: 'openrouter',
    name: 'Gemini 2.0 Flash (OR)',
    description: 'Gemini 2.0 Flash via OpenRouter',
    contextTokens: 1_048_576,
    pricing: { input: 0.1, output: 0.4 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 80, writing: 78 },
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    provider: 'openrouter',
    name: 'Llama 3.3 70B (OR)',
    description: 'Llama 3.3 via OpenRouter — open-source strength',
    contextTokens: 128_000,
    pricing: { input: 0.39, output: 0.39 },
    ratings: { extraction: 83, synthesis: 82, reasoning: 82, writing: 81 },
  },
  {
    id: 'meta-llama/llama-3.1-405b-instruct',
    provider: 'openrouter',
    name: 'Llama 3.1 405B (OR)',
    description: 'Largest open model via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 2.0, output: 2.0 },
    ratings: { extraction: 90, synthesis: 89, reasoning: 90, writing: 88 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    provider: 'openrouter',
    name: 'Llama 3.1 8B (OR)',
    description: 'Compact Llama via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.06, output: 0.06 },
    ratings: { extraction: 68, synthesis: 65, reasoning: 62, writing: 64 },
  },
  {
    id: 'deepseek/deepseek-r1',
    provider: 'openrouter',
    name: 'DeepSeek R1 (OR)',
    description: 'DeepSeek R1 — advanced reasoning via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.55, output: 2.19 },
    ratings: { extraction: 85, synthesis: 84, reasoning: 92, writing: 82 },
  },
  {
    id: 'deepseek/deepseek-chat-v3-0324',
    provider: 'openrouter',
    name: 'DeepSeek V3 (OR)',
    description: 'DeepSeek V3 chat model — excellent value',
    contextTokens: 128_000,
    pricing: { input: 0.27, output: 1.1 },
    ratings: { extraction: 82, synthesis: 81, reasoning: 84, writing: 80 },
  },
  {
    id: 'mistralai/mistral-large-2411',
    provider: 'openrouter',
    name: 'Mistral Large (OR)',
    description: 'Mistral Large via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 2.0, output: 6.0 },
    ratings: { extraction: 84, synthesis: 83, reasoning: 84, writing: 83 },
  },
  {
    id: 'mistralai/mistral-small-3.1-24b-instruct',
    provider: 'openrouter',
    name: 'Mistral Small 3.1 (OR)',
    description: 'Mistral Small — fast and efficient',
    contextTokens: 128_000,
    pricing: { input: 0.1, output: 0.3 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 70, writing: 72 },
  },
  {
    id: 'mistralai/mixtral-8x7b-instruct',
    provider: 'openrouter',
    name: 'Mixtral 8x7B (OR)',
    description: 'Mixtral via OpenRouter',
    contextTokens: 32_768,
    pricing: { input: 0.24, output: 0.24 },
    ratings: { extraction: 75, synthesis: 74, reasoning: 73, writing: 74 },
  },
  {
    id: 'mistralai/codestral-2501',
    provider: 'openrouter',
    name: 'Codestral (OR)',
    description: 'Code-specialized Mistral model',
    contextTokens: 256_000,
    pricing: { input: 0.3, output: 0.9 },
    ratings: { extraction: 72, synthesis: 70, reasoning: 78, writing: 68 },
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    provider: 'openrouter',
    name: 'Qwen 2.5 72B (OR)',
    description: 'Qwen 2.5 72B via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.36, output: 0.36 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 83, writing: 80 },
  },
  {
    id: 'qwen/qwq-32b',
    provider: 'openrouter',
    name: 'Qwen QwQ 32B (OR)',
    description: 'Qwen reasoning model via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.2, output: 0.2 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 85, writing: 75 },
  },
  {
    id: 'qwen/qwen3-235b-a22b',
    provider: 'openrouter',
    name: 'Qwen 3 235B (OR)',
    description: 'Largest Qwen 3 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.88, output: 0.88 },
    ratings: { extraction: 88, synthesis: 86, reasoning: 89, writing: 86 },
  },
  {
    id: 'qwen/qwen3-32b',
    provider: 'openrouter',
    name: 'Qwen 3 32B (OR)',
    description: 'Qwen 3 32B via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.2, output: 0.2 },
    ratings: { extraction: 80, synthesis: 78, reasoning: 82, writing: 78 },
  },
  {
    id: 'cohere/command-r-plus',
    provider: 'openrouter',
    name: 'Command R+ (OR)',
    description: 'Cohere Command R+ — strong for RAG and retrieval',
    contextTokens: 128_000,
    pricing: { input: 2.5, output: 10.0 },
    ratings: { extraction: 86, synthesis: 84, reasoning: 82, writing: 83 },
  },
  {
    id: 'cohere/command-a',
    provider: 'openrouter',
    name: 'Command A (OR)',
    description: 'Cohere Command A — latest generation',
    contextTokens: 256_000,
    pricing: { input: 2.5, output: 10.0 },
    ratings: { extraction: 87, synthesis: 85, reasoning: 84, writing: 85 },
  },
  {
    id: 'x-ai/grok-3-beta',
    provider: 'openrouter',
    name: 'Grok 3 Beta (OR)',
    description: 'xAI Grok 3 — competitive flagship model',
    contextTokens: 131_072,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 88, synthesis: 87, reasoning: 90, writing: 86 },
  },
  {
    id: 'x-ai/grok-3-mini-beta',
    provider: 'openrouter',
    name: 'Grok 3 Mini (OR)',
    description: 'xAI Grok 3 Mini — fast reasoning',
    contextTokens: 131_072,
    pricing: { input: 0.3, output: 0.5 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 82, writing: 75 },
  },
  {
    id: 'microsoft/phi-4',
    provider: 'openrouter',
    name: 'Phi 4 (OR)',
    description: 'Microsoft Phi 4 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0.07, output: 0.07 },
    ratings: { extraction: 74, synthesis: 72, reasoning: 78, writing: 71 },
  },
  {
    id: 'perplexity/sonar-pro',
    provider: 'openrouter',
    name: 'Sonar Pro (OR)',
    description: 'Perplexity search-augmented model',
    contextTokens: 200_000,
    pricing: { input: 3.0, output: 15.0 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 78, writing: 78 },
  },
  {
    id: 'perplexity/sonar',
    provider: 'openrouter',
    name: 'Sonar (OR)',
    description: 'Perplexity basic search model',
    contextTokens: 128_000,
    pricing: { input: 1.0, output: 1.0 },
    ratings: { extraction: 75, synthesis: 73, reasoning: 70, writing: 72 },
  },
  {
    id: 'amazon/nova-pro-v1',
    provider: 'openrouter',
    name: 'Amazon Nova Pro (OR)',
    description: 'AWS Nova Pro via OpenRouter',
    contextTokens: 300_000,
    pricing: { input: 0.8, output: 3.2 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 76, writing: 75 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    provider: 'openrouter',
    name: 'Nemotron 70B (OR)',
    description: 'NVIDIA Nemotron — fine-tuned Llama',
    contextTokens: 128_000,
    pricing: { input: 0.39, output: 0.39 },
    ratings: { extraction: 82, synthesis: 80, reasoning: 82, writing: 79 },
  },
  {
    id: 'nousresearch/hermes-3-llama-3.1-405b',
    provider: 'openrouter',
    name: 'Hermes 3 405B (OR)',
    description: 'NousResearch Hermes — largest open instruction-tuned',
    contextTokens: 128_000,
    pricing: { input: 2.0, output: 2.0 },
    ratings: { extraction: 88, synthesis: 86, reasoning: 88, writing: 86 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct:free',
    provider: 'openrouter',
    name: 'Llama 3.1 8B (Free)',
    description: 'Free Llama 3.1 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 68, synthesis: 65, reasoning: 62, writing: 64 },
  },
  {
    id: 'qwen/qwen3-8b:free',
    provider: 'openrouter',
    name: 'Qwen 3 8B (Free)',
    description: 'Free Qwen 3 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 70, synthesis: 68, reasoning: 72, writing: 68 },
  },
  {
    id: 'google/gemma-3-27b-it:free',
    provider: 'openrouter',
    name: 'Gemma 3 27B (Free)',
    description: 'Free Google Gemma 3 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 78, synthesis: 76, reasoning: 75, writing: 75 },
  },
  {
    id: 'deepseek/deepseek-r1:free',
    provider: 'openrouter',
    name: 'DeepSeek R1 (Free)',
    description: 'Free DeepSeek R1 via OpenRouter',
    contextTokens: 128_000,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 85, synthesis: 84, reasoning: 92, writing: 82 },
  },
  {
    id: 'mistralai/mistral-7b-instruct:free',
    provider: 'openrouter',
    name: 'Mistral 7B (Free)',
    description: 'Free Mistral 7B via OpenRouter',
    contextTokens: 32_768,
    pricing: { input: 0, output: 0 },
    ratings: { extraction: 68, synthesis: 66, reasoning: 64, writing: 66 },
  },
];

export function getModelsForProvider(provider: string): ModelSpec[] {
  return MODEL_REGISTRY.filter((m) => m.provider === provider);
}

export function getModelById(id: string): ModelSpec | undefined {
  return MODEL_REGISTRY.find((m) => m.id === id);
}

export function avgRating(m: ModelSpec): number {
  const r = m.ratings;
  return Math.round((r.extraction + r.synthesis + r.reasoning + r.writing) / 4);
}

export function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return String(n);
}

export function formatCost(n: number): string {
  if (n === 0) return 'Free';
  if (n < 0.01) return '<$0.01';
  return `$${n.toFixed(2)}`;
}

/**
 * Estimate quality ratings from OpenRouter API quality scores + pricing.
 * Maps: extraction ≈ instruction, synthesis ≈ overall, reasoning, writing ≈ avg(overall+instruction).
 */
export function estimateRatingsFromApi(
  qualityScores: {
    overall?: number;
    reasoning?: number;
    coding?: number;
    instruction?: number;
  } | null,
  pricingInputPerM: number,
): { extraction: number; synthesis: number; reasoning: number; writing: number } {
  if (qualityScores && qualityScores.overall != null) {
    const overall = qualityScores.overall;
    const reasoning = qualityScores.reasoning ?? overall;
    const instruction = qualityScores.instruction ?? overall;
    return {
      extraction: Math.round(instruction * 0.8 + overall * 0.2),
      synthesis: Math.round(overall),
      reasoning: Math.round(reasoning),
      writing: Math.round((overall + instruction) / 2),
    };
  }
  // Estimate from price tier
  if (pricingInputPerM >= 10) return { extraction: 88, synthesis: 90, reasoning: 92, writing: 89 };
  if (pricingInputPerM >= 3) return { extraction: 85, synthesis: 86, reasoning: 87, writing: 85 };
  if (pricingInputPerM >= 1) return { extraction: 80, synthesis: 80, reasoning: 80, writing: 80 };
  if (pricingInputPerM >= 0.1) return { extraction: 72, synthesis: 70, reasoning: 70, writing: 70 };
  return { extraction: 65, synthesis: 63, reasoning: 60, writing: 62 };
}

/**
 * Agent-specific fit scores (1–10 scale) based on model capabilities.
 * Ported from Lexio's `inferFitScores()` pattern.
 */
export type AgentFitKey =
  | 'summarize'
  | 'actionItems'
  | 'mindmap'
  | 'chapters'
  | 'chat'
  | 'embed'
  | 'transcribe';

const AGENT_WEIGHT_MAP: Record<
  AgentFitKey,
  { extraction: number; synthesis: number; reasoning: number; writing: number }
> = {
  summarize: { extraction: 0.2, synthesis: 0.35, reasoning: 0.15, writing: 0.3 },
  actionItems: { extraction: 0.4, synthesis: 0.2, reasoning: 0.2, writing: 0.2 },
  mindmap: { extraction: 0.3, synthesis: 0.3, reasoning: 0.25, writing: 0.15 },
  chapters: { extraction: 0.35, synthesis: 0.25, reasoning: 0.2, writing: 0.2 },
  chat: { extraction: 0.15, synthesis: 0.2, reasoning: 0.35, writing: 0.3 },
  embed: { extraction: 0.5, synthesis: 0.3, reasoning: 0.1, writing: 0.1 },
  transcribe: { extraction: 0.6, synthesis: 0.1, reasoning: 0.1, writing: 0.2 },
};

export function inferFitScore(model: ModelSpec, agentKey: AgentFitKey): number {
  const weights = AGENT_WEIGHT_MAP[agentKey];
  const r = model.ratings;
  const raw =
    r.extraction * weights.extraction +
    r.synthesis * weights.synthesis +
    r.reasoning * weights.reasoning +
    r.writing * weights.writing;
  // Map 0–100 rating → 1–10 scale
  return Math.max(1, Math.min(10, Math.round(raw / 10)));
}

export function isModelCompatibleWithAgent(model: ModelSpec, agentKey: AgentFitKey): boolean {
  const haystack = `${model.id} ${model.name} ${model.description}`.toLowerCase();

  if (agentKey === 'embed') {
    return haystack.includes('embed') || haystack.includes('embedding');
  }

  if (agentKey === 'transcribe') {
    return (
      haystack.includes('whisper') ||
      haystack.includes('transcribe') ||
      haystack.includes('speech') ||
      haystack.includes('stt')
    );
  }

  return inferFitScore(model, agentKey) >= 5;
}

/**
 * Convert an OpenRouter API model to a ModelSpec.
 * Ported from Lexio's `openRouterToModelOption()`.
 */
export function openRouterToModelSpec(apiModel: {
  id: string;
  name?: string;
  description?: string;
  context_length?: number;
  pricing?: { prompt?: string; completion?: string };
  quality_scores?: { overall?: number; reasoning?: number; coding?: number; instruction?: number };
}): ModelSpec {
  const inputPerM = apiModel.pricing?.prompt ? Number(apiModel.pricing.prompt) * 1_000_000 : 0;
  const outputPerM = apiModel.pricing?.completion
    ? Number(apiModel.pricing.completion) * 1_000_000
    : 0;
  return {
    id: apiModel.id,
    provider: 'openrouter',
    name: apiModel.name ?? apiModel.id.split('/').pop() ?? apiModel.id,
    description: apiModel.description ?? '',
    contextTokens: apiModel.context_length ?? 128_000,
    pricing: { input: inputPerM, output: outputPerM },
    ratings: estimateRatingsFromApi(apiModel.quality_scores ?? null, inputPerM),
  };
}
